server:
  port: 9093
  servlet:
    context-path: /webmvc-demo
project:
  version: '@project.version@'
spring:
  profiles:
    active: review
  application:
    name: webmvc-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui
    enabled: true
    validator-url: none
code:
  log:
    dir: logs
  lib:
    dir: ./lib
