server:
  port: 9093
  servlet:
    context-path: /demo
project:
  version: '@project.version@'
spring:
  profiles:
    active: review
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
